module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  important: true,
  theme: {
    colors: {
      'primary-color': '#2e86c1',
      'secondary-color': '#efa2a4',
      'ternary-color': '#f4d03f',

      'primary-color-dark': '#ffb710',
      'primary-color-dark-10': '#f3b503',
      'primary-color-dark-20': '#cca412',
      'primary-color-dark-30': '#b28f10',
      'primary-color-dark-40': '#997b0d',
      'primary-color-dark-50': '#7f660b',

      'primary-color-light-10': '#ffd22e',
      'primary-color-light-20': '#ffd745',
      'primary-color-light-30': '#ffdc5c',
      'primary-color-light-40': '#ffe173',
      'primary-color-light-50': '#ffe68b',
      'primary-color-light-60': '#ffeba2',
      'primary-color-light-70': '#fff0b9',
      'primary-color-light-80': '#fff5d0',
      'primary-color-light-90': '#fffae7',

      'info-color': '#5487f5',
      'info-color-light': '#e5edfe',
      'success-color': '#00c48c',
      'success-color-light': '#d9f6ee',
      'alert-color': '#fba707',
      'alert-color-light': '#fff8e7',
      'warning-color': '#ff934b',
      'warning-color-light': '#fff1e9',
      'error-color': '#f74360',
      'error-color-light': '#ffe8eb',

      'color-gray-10': '#1e2328',
      'color-gray-20': '#34383d',
      'color-gray-30': '#616568',
      'color-gray-40': '#8e9193',
      'color-gray-50': '#bbbdbe',
      'color-gray-60': '#e8e9e9',

      'color-dark-mode-10': '#78777A',
      'color-dark-mode-20': '#616064',
      'color-dark-mode-30': '#4A4A4E',
      'color-dark-mode-40': '#232228',
      'color-dark-mode-50': '#1E1D22',
      'color-dark-mode-60': '#232228',
      'color-dark-mode-70': '#17161B',
      'color-dark-mode-80': '#100F12',

      'surface-primary': '#ffffff',
      'surface-secondary': '#f7fafc',
      'surface-light': '#d5d5dc',
      'surface-dark': '#070632',
      'surface-orange': '#fff8e7',
      'surface-white': '#fcedeb',
      'surface-grey': '#f4f7ff',
      'surface-tertiary-10': '#f4f4f4',
      'surface-tertiary-20': '#e8f1ff',
      'surface-tertiary-30': '#f7f8f9',

      'color-accent-orange': '#FFA564',
      'color-accent-orange-light': '#FFF7EB',
      'color-accent-blue': '#52ACFF',
      'color-accent-blue-light': '#D4F0FF',
      'color-accent-green': '#5AD7D5',
      'color-accent-green-light': '#DEFFEB',
      'color-accent-purple': '#9375FF',
      'color-accent-purple-light': '#ECE9FF',
      'color-accent-pink': '#FF8A9F',
      'color-accent-pink-light': '#FFF2FB',
      'color-accent-yellow': '#FEBF49',
      'color-accent-yellow-light': '#FEF5D7',
      'color-accent-sky': '#3CBBDA',
      'color-accent-sky-light': '#C6F4FF',
      'color-accent-fuchsia': '#D85698',
      'color-accent-fuchsia-light': '#FFDBED',
      'color-accent-lime': '#A2DF37',
      'color-accent-lime-light': '#ECFCD1',

      'color-dark-blue': '#45445f',
      'disabled-color': '#b1b7cc',
      'cancel-color': '#e9ecf7',
      'color-orange': '#ffb710',
    },
    screens: {
      sm: '576px',
      md: '768px',
      lg: '992px',
      xl: '1200px',
      '2xl': '1600px',
    },
  },
  plugins: [],
};
